[package]
name = "re_log"
version.workspace = true
edition.workspace = true

[features]
default = []
setup = []

[dependencies]
tracing-log = { workspace = true, optional = true }
tracing-subscriber.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
tracing.workspace = true
log-once.workspace = true
anyhow.workspace = true
